"""Generate sql/seed_workpaper.sql from the Human Capital workbook.

Usage:
    python3 scripts/generate_seed.py <workbook.xlsx> > sql/seed_workpaper.sql

Reuses parse_workpaper.parse_unit_sheet so the SQL always reflects the latest
workbook. Levels resolve to the shared `roles` master table and job titles
resolve to the `positions` master table (created if missing) rather than
being stored as free text. Amount tiers are NOT generated here — they are
global master data seeded once in sql/seed.sql and referenced by sequence.

The output is idempotent for work_units/workpaper_rows/workpaper_authority/
ses_entries (truncated and re-inserted every run); positions are additive
(ON CONFLICT DO NOTHING) since they are shared master data.
"""

import sys

import openpyxl

from parse_workpaper import norm, parse_unit_sheet

# The workbook spells this "Departement Head" (typo); the roles master uses
# the corrected spelling.
LEVEL_ALIASES = {
    "Departement Head": "Department Head",
}

ROW_KIND_ROLE = {
    "buyer": "Buyer",
    "creator": "PR Creator",
}


def sq(v):
    """SQL string literal (or NULL)."""
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def entity_code_of(sheet_title):
    # 'IMU-FIN' -> 'IMU', 'MBN-ALL SITE' -> 'MBN'
    return sheet_title.split("-")[0].split(" ")[0].strip()


def role_name_for(row):
    if row["kind"] == "authority":
        return LEVEL_ALIASES.get(row["level"], row["level"])
    return ROW_KIND_ROLE.get(row["kind"])


def main():
    path = sys.argv[1]
    wb = openpyxl.load_workbook(path, data_only=True)

    units = []
    for ws in wb.worksheets:
        title = ws.title
        if title == "Sheet1" or "not use" in title.lower() or title == "IMU":
            continue
        parsed = parse_unit_sheet(ws)
        if parsed:
            parsed["code"] = title
            parsed["entity_code"] = entity_code_of(title)
            units.append(parsed)

    # Entity code -> legal name (first sheet wins).
    entities = {}
    for u in units:
        entities.setdefault(u["entity_code"], u["entity_name"])

    # Distinct job titles across every row, to seed as master positions.
    positions = sorted({
        r["position"] for u in units for r in u["rows"] if r["position"]
    })

    out = []
    w = out.append
    w("-- Auto-generated by scripts/generate_seed.py — do not edit by hand.")
    w("-- Source: Human Capital 'Workflow Approval' workbook.\n")
    w("BEGIN;\n")
    w("TRUNCATE ses_entries, workpaper_authority, workpaper_rows,")
    w("         work_units RESTART IDENTITY CASCADE;\n")

    # Refresh entity legal names (entities themselves are seeded in seed.sql;
    # here we only correct the display name from the authoritative workbook).
    for code, name in sorted(entities.items()):
        w(f"UPDATE entities SET name = {sq(name)} WHERE code = {sq(code)};")
    w("")

    w("-- Job titles: additive master data, never reset by a re-import.")
    for title in positions:
        w(f"INSERT INTO positions (title) VALUES ({sq(title)}) ON CONFLICT (title) DO NOTHING;")
    w("")

    w("DO $$")
    w("DECLARE v_unit INTEGER; v_row INTEGER;")
    w("BEGIN")
    for order, u in enumerate(units):
        ec = u["entity_code"]
        w(f"  -- {u['code']} ({u['project_name']})")
        w(
            "  INSERT INTO work_units (entity_id, code, project_name, sort_order) "
            f"SELECT id, {sq(u['code'])}, {sq(u['project_name'])}, {order} "
            f"FROM entities WHERE code = {sq(ec)} RETURNING id INTO v_unit;"
        )
        for seq, r in enumerate(u["rows"]):
            role_name = role_name_for(r)
            position_expr = (
                f"(SELECT id FROM positions WHERE title = {sq(r['position'])})"
                if r["position"] else "NULL"
            )
            w(
                "  INSERT INTO workpaper_rows "
                "(work_unit_id, row_kind, seq, role_id, person_name, position_id, comment) "
                f"VALUES (v_unit, {sq(r['kind'])}, {seq}, "
                f"(SELECT id FROM roles WHERE name = {sq(role_name)}), "
                f"{sq(r['name'])}, {position_expr}, {sq(r['comment'])}) RETURNING id INTO v_row;"
            )
            if r["kind"] == "authority":
                for band_seq, required in sorted(r["bands"].items()):
                    w(
                        "  INSERT INTO workpaper_authority (row_id, tier_id, required) "
                        f"SELECT v_row, id, {'TRUE' if required else 'FALSE'} "
                        f"FROM amount_tiers WHERE seq = {int(band_seq)};"
                    )
        for s in u["ses"]:
            # match SES row to a tier by its band label text
            try:
                band_seq = u["bands"].index(norm(s["band_label"]))
            except ValueError:
                band_seq = _closest_band(u["bands"], s["band_label"])
            if band_seq is None:
                continue
            w(
                "  INSERT INTO ses_entries (work_unit_id, tier_id, creator_name, approver_name) "
                f"SELECT v_unit, id, {sq(s['creator'])}, {sq(s['approver'])} "
                f"FROM amount_tiers WHERE seq = {band_seq};"
            )
    w("END $$;\n")
    w("COMMIT;")
    print("\n".join(out))


def _closest_band(bands, label):
    label = norm(label)
    for i, b in enumerate(bands):
        if norm(b) == label:
            return i
    # fall back to prefix match on the first amount token
    key = label[:12]
    for i, b in enumerate(bands):
        if norm(b).startswith(key):
            return i
    return None


if __name__ == "__main__":
    main()
