"""Generate sql/seed_workpaper.sql from the Human Capital workbook.

Usage:
    python3 scripts/generate_seed.py <workbook.xlsx> > sql/seed_workpaper.sql

Reuses parse_workpaper.parse_unit_sheet so the SQL always reflects the latest
workbook. The output is idempotent: it truncates the workpaper tables and
re-inserts everything inside a single transaction.
"""

import sys

import openpyxl

from parse_workpaper import norm, parse_unit_sheet


def sq(v):
    """SQL string literal (or NULL)."""
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def entity_code_of(sheet_title):
    # 'IMU-FIN' -> 'IMU', 'MBN-ALL SITE' -> 'MBN'
    return sheet_title.split("-")[0].split(" ")[0].strip()


def main():
    path = sys.argv[1]
    wb = openpyxl.load_workbook(path, data_only=True)

    units = []
    for ws in wb.worksheets:
        title = ws.title
        if title == "Sheet1" or "not use" in title.lower() or title == "IMU":
            continue
        parsed = parse_unit_sheet(ws)
        if parsed:
            parsed["code"] = title
            parsed["entity_code"] = entity_code_of(title)
            units.append(parsed)

    # Entity code -> legal name (first sheet wins).
    entities = {}
    for u in units:
        entities.setdefault(u["entity_code"], u["entity_name"])

    out = []
    w = out.append
    w("-- Auto-generated by scripts/generate_seed.py — do not edit by hand.")
    w("-- Source: Human Capital 'Workflow Approval' workbook.\n")
    w("BEGIN;\n")
    w("TRUNCATE ses_entries, workpaper_authority, workpaper_rows,")
    w("         threshold_bands, work_units RESTART IDENTITY CASCADE;\n")

    # Refresh entity legal names (entities themselves are seeded in seed.sql;
    # here we only correct the display name from the authoritative workbook).
    for code, name in sorted(entities.items()):
        w(f"UPDATE entities SET name = {sq(name)} WHERE code = {sq(code)};")
    w("")

    # Threshold bands: use each entity's first unit as the band definition.
    bands_done = set()
    for u in units:
        ec = u["entity_code"]
        if ec in bands_done:
            continue
        bands_done.add(ec)
        for seq, label in enumerate(u["bands"]):
            w(
                "INSERT INTO threshold_bands (entity_id, seq, label) "
                f"SELECT id, {seq}, {sq(label)} FROM entities WHERE code = {sq(ec)};"
            )
    w("")

    w("DO $$")
    w("DECLARE v_unit INTEGER; v_row INTEGER;")
    w("BEGIN")
    for order, u in enumerate(units):
        ec = u["entity_code"]
        w(f"  -- {u['code']} ({u['project_name']})")
        w(
            "  INSERT INTO work_units (entity_id, code, project_name, sort_order) "
            f"SELECT id, {sq(u['code'])}, {sq(u['project_name'])}, {order} "
            f"FROM entities WHERE code = {sq(ec)} RETURNING id INTO v_unit;"
        )
        for seq, r in enumerate(u["rows"]):
            w(
                "  INSERT INTO workpaper_rows "
                "(work_unit_id, row_kind, seq, level_label, person_name, position, comment) "
                f"VALUES (v_unit, {sq(r['kind'])}, {seq}, {sq(r['level'])}, "
                f"{sq(r['name'])}, {sq(r['position'])}, {sq(r['comment'])}) RETURNING id INTO v_row;"
            )
            if r["kind"] == "authority":
                for band_seq, required in sorted(r["bands"].items()):
                    w(
                        "  INSERT INTO workpaper_authority (row_id, band_id, required) "
                        f"SELECT v_row, id, {'TRUE' if required else 'FALSE'} FROM threshold_bands "
                        f"WHERE entity_id = (SELECT entity_id FROM work_units WHERE id = v_unit) "
                        f"AND seq = {int(band_seq)};"
                    )
        for s in u["ses"]:
            # match SES row to a band by label
            try:
                band_seq = u["bands"].index(norm(s["band_label"]))
            except ValueError:
                band_seq = _closest_band(u["bands"], s["band_label"])
            if band_seq is None:
                continue
            w(
                "  INSERT INTO ses_entries (work_unit_id, band_id, creator_name, approver_name) "
                f"SELECT v_unit, id, {sq(s['creator'])}, {sq(s['approver'])} FROM threshold_bands "
                f"WHERE entity_id = (SELECT entity_id FROM work_units WHERE id = v_unit) "
                f"AND seq = {band_seq};"
            )
    w("END $$;\n")
    w("COMMIT;")
    print("\n".join(out))


def _closest_band(bands, label):
    label = norm(label)
    for i, b in enumerate(bands):
        if norm(b) == label:
            return i
    # fall back to prefix match on the first amount token
    key = label[:12]
    for i, b in enumerate(bands):
        if norm(b).startswith(key):
            return i
    return None


if __name__ == "__main__":
    main()
