"""Generate sql/seed_users.sql: initial CRUD-access accounts.

Usage:
    python3 scripts/seed_users.py > ../sql/seed_users.sql

Uses ON CONFLICT (email) DO NOTHING so re-running never resets a password
someone has already changed.
"""

from werkzeug.security import generate_password_hash

DEFAULT_PASSWORD = "20interporT26!"

USERS = [
    "Muhammad.Althaf@interport.co.id",
    "Muhammad.Shubkhi@interport.co.id",
    "Humaira.Khoirunnisa@interport.co.id",
]


def sq(v):
    return "'" + v.replace("'", "''") + "'"


def full_name_from_email(email):
    local = email.split("@", 1)[0]
    return " ".join(part.capitalize() for part in local.split("."))


def main():
    print("-- Auto-generated by scripts/seed_users.py — do not edit by hand.")
    print("-- Default password for all accounts below:", DEFAULT_PASSWORD)
    print("-- Existing users are left untouched (safe to re-run).\n")
    for email in USERS:
        full_name = full_name_from_email(email)
        password_hash = generate_password_hash(DEFAULT_PASSWORD)
        print(
            "INSERT INTO users (email, full_name, password_hash, must_change_password) "
            f"VALUES ({sq(email)}, {sq(full_name)}, {sq(password_hash)}, TRUE) "
            "ON CONFLICT (email) DO NOTHING;"
        )


if __name__ == "__main__":
    main()
