-- Auto-generated by scripts/seed_users.py — do not edit by hand.
-- Default password for all accounts below: 20interporT26!
-- Existing users are left untouched (safe to re-run).

INSERT INTO users (email, full_name, password_hash, must_change_password) VALUES ('Muhammad.Althaf@interport.co.id', 'Muhammad Althaf', 'scrypt:32768:8:1$yo3PAhrCDBNrCUoW$3df205591837a54db63f07a19169e259f1c6cf0442eb4348791d996d9c0ab9db9b3f46904049ba265b28be21b2b49da9026aff0afd95011bd15a06b110a66dd6', TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO users (email, full_name, password_hash, must_change_password) VALUES ('Muhammad.Shubkhi@interport.co.id', 'Muhammad Shubkhi', 'scrypt:32768:8:1$jrqrjD6U6P8tcnkp$26994072d245d917b33fc6e01e3807dc1eea7edf43e725a12973d74f84046533563b8468890509a6aedbeaf23791d2d0cb97b9beea0b83861ccf58e1dcfa4bdc', TRUE) ON CONFLICT (email) DO NOTHING;
INSERT INTO users (email, full_name, password_hash, must_change_password) VALUES ('Humaira.Khoirunnisa@interport.co.id', 'Humaira Khoirunnisa', 'scrypt:32768:8:1$ZvdTk3G6pJ05S1gw$9f22a83d4a9809a583edc0d3e1c9b1f5d623ad63ae87f851496a95c1d55acab0226a907bd88be1638d11002bdd58e9cc4bb2849dbcc9df1e599a2e651f379d2c', TRUE) ON CONFLICT (email) DO NOTHING;
